# Generated by Django 3.1 on 2020-09-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
    ]
