# Generated by Django 3.1 on 2020-09-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
    ]
