# Generated by Django 3.1 on 2020-10-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201002_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
    ]
